### ISSUE TITLE
License for the project

### ISSUE THREAD

**Issue by DrDub** [evykassirer/whatprivilege#12]
Hi!

Nice project. Is it available under any open source license?

Best regards,

P

**Comment by evykassirer** [comment]
Thanks! I made this before I knew about open source licenses, but you're welcome to fork it and use it :)

**Comment by DrDub** [comment]
Thanks, you're very kind. 

If I send a contribution to the project, under which license it'll be available?

**Comment by evykassirer** [comment]
I've heard the Apache License is good, so let's go by that :)

**Comment by DrDub** [comment]
I realized the website makes clear the licence is CC-BY-NC and that there are two other authors (which makes changing licences more complicated). As such, I'm closing the issue, as the licence is clear. You might want to add something about CC-BY-NC to the readme.

 (As a personal note, I do not endorse NC licences as they are FSF/OSI/DFSG non-free, but licencing is a very, very personal matter.)
